name: update Calendar JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run update
      - name: commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add year25.json
          git commit -m "update calendar JSON"
          git push
